version: '3.8'
services:
  db:
    image: postgres:16.4
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: sauronx2
      POSTGRES_PASSWORD: qwe12345
      POSTGRES_DB: nestjs
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
